import { randomInt } from "crypto";

const WORDS = [
  "ace", "air", "ant", "ape", "arc", "arm", "art", "ash", "bay", "bee",
  "bet", "bin", "bit", "bow", "box", "bud", "bug", "bus", "cab", "cam",
  "cap", "car", "cat", "cod", "cow", "cub", "cup", "day", "den", "dew",
  "dig", "dim", "dot", "dry", "dub", "dug", "ear", "egg", "elm", "emu",
  "end", "eye", "fan", "far", "fig", "fin", "fit", "fix", "fly", "foe",
  "fox", "fun", "fur", "gap", "gem", "gin", "gnu", "gum", "gun", "gut",
  "gym", "ham", "hat", "hay", "hen", "hip", "hop", "hot", "hub", "hue",
  "hug", "ice", "ink", "ivy", "jam", "jar", "jaw", "jet", "job", "jog",
  "joy", "jug", "key", "kid", "kit", "lab", "lag", "lap", "law", "lay",
  "leg", "lid", "lip", "lit", "log", "lot", "low", "map", "mat", "max",
  "mix", "mob", "mop", "mud", "mug", "nap", "net", "new", "nod", "nut",
  "oak", "oar", "oat", "odd", "oil", "old", "one", "opt", "orb", "ore",
  "owl", "pad", "pal", "pan", "paw", "pea", "peg", "pen", "pet", "pie",
  "pig", "pin", "pit", "pod", "pop", "pot", "pro", "pub", "pug", "pun",
  "pup", "put", "ram", "rap", "rat", "raw", "ray", "red", "rib", "rim",
  "rip", "rob", "rod", "row", "rub", "rug", "run", "rye", "sad", "sap",
  "sat", "saw", "sea", "set", "sew", "sip", "sir", "sit", "six", "ski",
  "sky", "sly", "sob", "sod", "son", "spa", "spy", "sub", "sum", "sun",
  "tab", "tag", "tan", "tap", "tar", "tax", "tea", "ten", "tie", "tin",
  "tip", "toe", "ton", "top", "tow", "toy", "try", "tub", "tug", "two",
  "urn", "use", "van", "vat", "vet", "vim", "vow", "wag", "war", "wax",
  "way", "web", "wet", "wig", "win", "wit", "woe", "wok", "won", "wow",
  "yak", "yam", "yap", "yaw", "yes", "yet", "yew", "zap", "zen", "zip",
  "blue", "bold", "calm", "cave", "clay", "coal", "cool", "crop", "dark",
  "dawn", "deck", "deep", "dirt", "dock", "dome", "dove", "drop", "dune",
  "dust", "edge", "fair", "fall", "farm", "fast", "fawn", "fear", "fern",
  "film", "fire", "fish", "flag", "flat", "flea", "flow", "foam", "fold",
  "fork", "form", "free", "frog", "fuel", "fuse", "gale", "gate", "glow",
  "gold", "golf", "gray", "grin", "grow", "gulf", "hail", "half", "hand",
  "hard", "harm", "hawk", "haze", "head", "heap", "heat", "help", "herb",
  "hero", "hill", "hive", "hold", "hole", "home", "hood", "hook", "hope",
  "horn", "host", "hunt", "idea", "iron", "item", "jade", "jazz", "join",
  "joke", "jump", "just", "keen", "keep", "kick", "kind", "king", "kite",
  "knee", "knob", "knot", "lace", "lake", "lamp", "land", "lane", "lark",
  "lava", "leaf", "leap", "lens", "life", "lift", "lime", "line", "link",
  "lion", "list", "live", "loaf", "loan", "lock", "loft", "long", "look",
  "loop", "lord", "loud", "love", "luck", "luna", "lure", "lush", "mace",
  "mail", "main", "make", "mall", "mark", "mars", "mask", "mass", "mate",
  "maze", "mead", "meal", "mean", "meat", "melt", "memo", "menu", "mesh",
  "mild", "milk", "mill", "mind", "mine", "mint", "mist", "moat", "mock",
  "mode", "mold", "moon", "moor", "moss", "moth", "move", "much", "muse",
  "must", "myth", "nail", "name", "navy", "near", "neat", "neck", "need",
  "nest", "news", "nice", "nine", "node", "noon", "norm", "nose", "note",
  "nova", "oath", "obey", "odor", "okay", "olive", "once", "only", "open",
  "oral", "oval", "oven", "over", "pace", "pack", "page", "paid", "pail",
  "pain", "pair", "palm", "park", "part", "pass", "past", "path", "peak",
  "pear", "peel", "peer", "pick", "pier", "pile", "pine", "pink", "pipe",
  "plan", "play", "plot", "plug", "plum", "plus", "poem", "poet", "pole",
  "poll", "pond", "pool", "poor", "port", "post", "pour", "pray", "prey",
  "pull", "pump", "pure", "push", "race", "rack", "raft", "rail", "rain",
  "rank", "rare", "rate", "read", "real", "reed", "reef", "reel", "rest",
  "rice", "rich", "ride", "ring", "rise", "risk", "road", "roam", "roar",
  "robe", "rock", "role", "roll", "roof", "room", "root", "rope", "rose",
  "ruby", "ruin", "rule", "rush", "rust", "safe", "sage", "sail", "sale",
  "salt", "sand", "save", "scan", "seal", "seat", "seed", "seek", "self",
  "send", "shed", "ship", "shop", "shot", "show", "shut", "sick", "side",
  "sign", "silk", "sing", "sink", "site", "size", "skin", "skip", "slab",
  "slam", "slap", "slim", "slip", "slot", "slow", "slug", "snap", "snow",
  "soak", "soap", "soar", "sock", "soft", "soil", "sold", "sole", "some",
  "song", "sort", "soul", "soup", "sour", "span", "spin", "spot", "star",
  "stay", "stem", "step", "stew", "stir", "stop", "such", "suit", "sure",
  "surf", "swan", "swap", "swim", "tail", "take", "tale", "talk", "tall",
  "tank", "tape", "task", "team", "tear", "tell", "tent", "term", "test",
  "text", "than", "that", "them", "then", "they", "thin", "this", "tick",
  "tide", "tile", "till", "time", "tiny", "tire", "toad", "told", "toll",
  "tone", "took", "tool", "torn", "tour", "town", "trap", "tree", "trim",
  "trip", "true", "tube", "tuna", "tune", "turn", "twig", "type", "unit",
  "upon", "urge", "used", "user", "vain", "vale", "vast", "veil", "vein",
  "vent", "verb", "very", "vest", "vice", "view", "vine", "void", "vote",
  "wade", "wage", "wait", "wake", "walk", "wall", "wand", "want", "ward",
  "warm", "warn", "wash", "wave", "weak", "wear", "weed", "week", "well",
  "west", "whim", "whip", "wide", "wild", "will", "wind", "wine", "wing",
  "wink", "wipe", "wire", "wise", "wish", "wolf", "wood", "wool", "word",
  "work", "worm", "wrap", "yard", "yarn", "year", "yell", "yoga", "yolk",
  "zero", "zone", "zoom", "amber", "apple", "beach", "berry", "blade",
  "bliss", "bloom", "bluff", "board", "boost", "brave", "bread", "brick",
  "brief", "brook", "brush", "build", "candy", "cedar", "charm", "chase",
  "chill", "chord", "civic", "claim", "clasp", "clean", "clear", "cliff",
  "climb", "clock", "cloud", "clown", "coast", "coral", "couch", "cover",
  "crane", "creek", "crest", "crisp", "cross", "crowd", "crown", "curve",
  "daisy", "dance", "delta", "demon", "devil", "diver", "dodge", "draft",
  "drain", "dream", "drift", "drink", "drive", "drown", "eager", "eagle",
  "earth", "elder", "ember", "empty", "enjoy", "entry", "equal", "event",
  "extra", "fairy", "fancy", "fault", "feast", "field", "flame", "flash",
  "flint", "float", "flock", "flood", "flora", "flour", "flute", "focus",
  "force", "forge", "found", "frame", "fresh", "front", "frost", "fruit",
  "ghost", "giant", "glass", "glide", "globe", "glory", "grace", "grade",
  "grain", "grand", "grape", "grass", "gravy", "green", "greet", "grill",
  "grind", "group", "grove", "guard", "guess", "guest", "guide", "happy",
  "harsh", "heart", "hence", "honey", "horse", "hotel", "house", "human",
  "humor", "ideal", "image", "index", "inner", "input", "ivory", "jewel",
  "joint", "judge", "juice", "knack", "knock", "label", "labor", "large",
  "laser", "later", "laugh", "layer", "lemon", "level", "light", "limit",
  "linen", "liver", "local", "logic", "lotus", "lover", "lower", "loyal",
  "lucky", "lunch", "magic", "major", "maple", "march", "match", "medal",
  "melon", "mercy", "merit", "metal", "meter", "micro", "might", "minor",
  "model", "money", "month", "moral", "motor", "mount", "mouse", "mouth",
  "movie", "music", "naked", "nerve", "never", "night", "noble", "noise",
  "north", "notch", "novel", "nurse", "ocean", "olive", "onion", "opera",
  "orbit", "order", "organ", "other", "outer", "owner", "paint", "panel",
  "paper", "party", "patch", "pause", "peace", "peach", "pearl", "penny",
  "phase", "phone", "photo", "piano", "piece", "pilot", "pitch", "pixel",
  "place", "plain", "plane", "plant", "plate", "plaza", "plead", "pluck",
  "point", "polar", "pouch", "power", "press", "price", "pride", "prime",
  "print", "prize", "proof", "proud", "prove", "pulse", "punch", "pupil",
  "queen", "quest", "quick", "quiet", "quote", "radar", "radio", "raise",
  "rally", "ranch", "range", "rapid", "ratio", "reach", "react", "ready",
  "realm", "rebel", "refer", "reign", "relax", "relay", "renew", "reply",
  "ridge", "right", "rigid", "rival", "river", "robin", "robot", "rocky",
  "roman", "rough", "round", "route", "royal", "rugby", "rural", "saint",
  "salad", "salon", "sandy", "sauce", "scale", "scarf", "scene", "scope",
  "score", "scout", "sense", "serve", "seven", "shade", "shake", "shall",
  "shame", "shape", "share", "sharp", "sheep", "sheet", "shelf", "shell",
  "shift", "shine", "shirt", "shock", "shoot", "shore", "short", "shout",
  "sight", "skill", "skirt", "skull", "slack", "slate", "sleep", "slice",
  "slide", "slope", "small", "smart", "smell", "smile", "smoke", "snack",
  "snake", "solar", "solid", "solve", "sound", "south", "space", "spare",
  "spark", "speak", "speed", "spell", "spend", "spice", "spine", "spite",
  "split", "spoke", "sport", "spray", "squad", "stack", "staff", "stage",
  "stain", "stake", "stand", "stark", "start", "state", "steak", "steam",
  "steel", "stick", "still", "stock", "stone", "store", "storm", "story",
  "strip", "study", "stuff", "style", "sugar", "suite", "sunny", "super",
  "surge", "sweet", "swift", "swing", "sword", "table", "taste", "teach",
  "tempo", "thank", "theme", "thick", "thing", "think", "third", "thorn",
  "those", "three", "throw", "thumb", "tiger", "tight", "timer", "title",
  "toast", "today", "token", "topic", "total", "touch", "tough", "tower",
  "toxic", "trace", "track", "trade", "trail", "train", "trait", "trash",
  "treat", "trend", "trial", "tribe", "trick", "troop", "truck", "truly",
  "trunk", "trust", "truth", "tulip", "tumor", "tuner", "twist", "uncle",
  "under", "union", "unity", "upper", "upset", "urban", "usage", "usual",
  "valid", "value", "vault", "vegan", "venue", "verse", "video", "vigor",
  "villa", "vinyl", "viola", "virus", "visit", "vital", "vivid", "vocal",
  "voice", "voter", "wagon", "waist", "waste", "watch", "water", "weary",
  "weave", "wheat", "wheel", "where", "which", "while", "white", "whole",
  "whose", "width", "witch", "woman", "world", "worry", "worth", "would",
  "wound", "write", "wrong", "yacht", "yield", "young", "youth", "zebra",
  "bottom", "branch", "bridge", "bright", "bronze", "bubble", "bucket",
  "buffer", "bundle", "butter", "button", "candle", "canvas", "carbon",
  "castle", "cattle", "center", "cherry", "circle", "clever", "clover",
  "coffee", "copper", "corner", "cotton", "couple", "course", "credit",
  "crystal", "custom", "danger", "decent", "desert", "detail", "device",
  "dinner", "doctor", "dollar", "donkey", "dragon", "drawer", "driver",
  "effect", "effort", "eleven", "empire", "energy", "engine", "escape",
  "estate", "ethics", "expert", "fabric", "factor", "falcon", "family",
  "farmer", "father", "fellow", "filter", "finger", "finish", "flower",
  "forest", "formal", "fossil", "friend", "future", "garden", "gather",
  "gentle", "giggle", "global", "golden", "govern", "gravel", "ground",
  "growth", "hammer", "handle", "harbor", "health", "heaven", "helmet",
  "hidden", "hollow", "honest", "horror", "humble", "hunter", "impact",
  "import", "income", "indoor", "insert", "intent", "invest", "island",
  "jacket", "jungle", "junior", "kernel", "kettle", "kitten", "knight",
  "ladder", "laptop", "launch", "lawyer", "leader", "league", "legend",
  "length", "lesson", "letter", "liquid", "listen", "little", "lively",
  "lizard", "locker", "lonely", "lounge", "lovely", "magnet", "manage",
  "manner", "marble", "margin", "market", "master", "matter", "medium",
  "member", "memory", "method", "middle", "minute", "mirror", "mobile",
  "modern", "moment", "monkey", "mother", "motion", "motive", "muscle",
  "museum", "mutual", "mystic", "native", "nature", "needle", "nerves",
  "nickel", "nobody", "normal", "notice", "number", "object", "obtain",
  "office", "online", "option", "orange", "origin", "output", "oxygen",
  "packet", "palace", "parent", "parrot", "patent", "people", "pepper",
  "period", "person", "phrase", "pickle", "picnic", "pillar", "pillow",
  "pirate", "planet", "player", "please", "plenty", "pocket", "poetry",
  "policy", "potato", "powder", "praise", "pretty", "profit", "prompt",
  "public", "purple", "rabbit", "racket", "random", "reason", "recall",
  "recent", "record", "reduce", "reflex", "regard", "region", "relief",
  "remote", "remove", "repair", "repeat", "report", "rescue", "result",
  "return", "review", "reward", "rhythm", "ribbon", "rocket", "rubber",
  "runner", "safety", "sample", "school", "screen", "script", "search",
  "season", "second", "secret", "sector", "select", "senior", "series",
  "server", "settle", "shadow", "shield", "signal", "silent", "silver",
  "simple", "singer", "single", "sister", "sketch", "smooth", "soccer",
  "social", "socket", "softly", "source", "spirit", "spring", "square",
  "stable", "statue", "status", "steady", "stereo", "sticky", "stream",
  "street", "stress", "strict", "strike", "string", "strong", "studio",
  "submit", "subtle", "sudden", "summer", "sunset", "supply", "surely",
  "switch", "symbol", "system", "tackle", "talent", "target", "temple",
  "tennis", "theory", "thread", "throat", "ticket", "timber", "tissue",
  "tomato", "tongue", "travel", "treaty", "tunnel", "turkey", "turtle",
  "unfair", "unique", "united", "unlock", "update", "useful", "vacuum",
  "valley", "vector", "velvet", "vendor", "vessel", "victim", "vision",
  "volume", "voyage", "wallet", "warmth", "weapon", "weight", "window",
  "winter", "wonder", "worker", "writer",   "yellow", "zenith",
].filter((word, index, list) => word.length <= 6 && list.indexOf(word) === index);

function pickWord() {
  return WORDS[randomInt(WORDS.length)];
}

export function generateRoomName() {
  return `${pickWord()}-${pickWord()}-${pickWord()}`;
}
